### ISSUE TITLE
PHP Parse Error

### ISSUE THREAD

**Issue by DoctorWhoFR** [doctrine/DoctrineCacheBundle#119]
AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/vhosts/doctorwhofr.stayhost.xyz/httpdocs/vendor/doctrine/doctrine-bundle/DependencyInjection/DoctrineExtension.php on line 814\n'

**Comment by xabbuh** [comment]
The error you mention is triggered by DoctrineBundle, but this is the issue tracker of DoctrineCacheBundle. And it looks like you using a version of DoctrineBundle that requires PHP 7 while you still use PHP 5.x.
