### ISSUE TITLE
Why this bundle does not have a Symfony recipe?

### ISSUE THREAD

**Issue by bocharsky-bw** [doctrine/DoctrineCacheBundle#131]
Can't find it on https://symfony.sh/

**Comment by alcaeus** [comment]
We haven't created one as of yet - I also have to admit that I haven't used flex at all yet so I'm not very familiar with what goes into a recipe. Would you be willing to contribute one?

**Comment by bocharsky-bw** [comment]
OK, sure!

**Comment by bocharsky-bw** [comment]
Done in https://github.com/symfony/recipes-contrib/pull/583

**Comment by alcaeus** [comment]
Recipe was added in PR above ans subsequently removed in https://github.com/symfony/recipes-contrib/pull/652. Closing here as this has been dealt with.
