### ISSUE TITLE
doctrine:cache:clear Fatal error: Class 'Memcached' not found 

### ISSUE THREAD

**Issue by BernardA** [doctrine/DoctrineCacheBundle#136]
Hello
With Symfony 3.3 whenever I try any combination of doctrine:cache:clear ( dev/prod), it will throw the error

> PHP Fatal error:  Class 'Memcached' not found in /Users/user/Sites/Symfony1/vendor/doctrine/doctrine-cache-bundle/Tests/Functional/Fixtures/Memcached.php on line 6

Also, I read somewhere that doctrine-cache-bundle might require doctrine-fixtures-bundle, and I tried to install that, but again  the same error is thrown on installation as per: 

> An error occurred when executing the "'cache:clear --no-warmup'" command:

I do have Memcached extension enabled on php ( Memcached version 3.0.4 as per phpinfo() ). Actually I am using Symfony's memcached adapter to cache query results per [:](http://symfony.com/doc/current/components/cache/adapters/memcached_adapter.html)

> use Symfony\Component\Cache\Adapter\MemcachedAdapter;

I have to say that I am more than a bit confused with the overlap between Symfony's cache, ORM cache and doctrine-cache-bundle. Not sure If or how to use them together and the documentation is not at all clear.

In any case, here is my config.yml

`    framework:
        cache: 
           app: cache.adapter.memcached 
            default_memcached_provider: "memcached://127.0.0.1:11211"
    ...
    orm:
        ...
        entity_managers:
           default:
                metadata_cache_driver: memcached
               result_cache_driver:
                   type: memcached
                   host: 127.0.0.1
                   port: 11211
                   instance_class: Memcached
               query_cache_driver: memcached

doctrine_cache:
    aliases: 
        mem_cached_meta: my_memcached_cache_metadata
        mem_cached_query: my_memcached_cache_query
        mem_cached_result: my_memcached_cache_result
    providers:
        my_memcached_cache_metadata: 
            type: memcached
            namespace: metadata_cache_ns
            aliases: 
                - mem_cached_meta
        my_memcached_cache_query: 
            type: memcached
            namespace: query_cache_ns
            aliases: 
                - mem_cached_query
        my_memcached_cache_result: 
            type: memcached
            namespace: result_cache_ns
            aliases: 
                - mem_cached_result`

**Comment by mikeSimonson** [comment]
Do you have memcahed installed (the php extension) ?

**Comment by BernardA** [comment]
Yes, as stated on my question above. Version 3.0.4 to be more specific and I am using it.

**Comment by mikeSimonson** [comment]
Does phpinfo (in the symfony dev toolbar) shows that extension enabled ?

**Comment by BernardA** [comment]
Yes, and again, I am actually using memcached on that app. So, enabled it is.

**Comment by BernardA** [comment]
Hang on now. Where do you mean? 
On the dev toolbal widget that shows when hovering Symfony's version, if I click on view phpinfo it will obviously show the php info where Memcached is enabled.
On the other hand on that same widget there is a PHP EXTENSIONS section. Memcached is not mentioned there at all. (xdebug, APCu, OPcache are shown - all in red in my case as I have OPcache disabled on MAMP ).

**Comment by mikeSimonson** [comment]
@BernardA Sorry but appart from saying that your setup is weird in some way, I can't help much as I don't even have mamp.
You should try to see if you can reproduce the issue using the php build in webserver with ```php -S 127.0.0.1``` to see but I suspect that something is broken in your setup not in your app or the doctrineCacheBundle.

**Comment by mookofe** [comment]
The problem seems to be this test: `Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Fixtures\Memcached`.

Somehow the autoloader is using that file as \Memcached.

```<?php
namespace Doctrine\Bundle\DoctrineCacheBundle\Tests\Functional\Fixtures;

class Memcached extends \Memcached
{

**Comment by jorenvh1** [comment]
Having the same error, is there a work around?

**Comment by alcaeus** [comment]
Closing here due to lack of feedback. @BernardA if the problem persists, please reopen the issue and outline more steps.

@mookofe while the class you highlighted uses the `\Memcached` class, the autoloader won't mistake the fixture class name for `\Memcached`. Either way, the latest version of this bundle excludes the `Tests` namespace from the classmap so the autoloader shouldn't know about this class anyways.

**Comment by The-Don-Himself** [comment]
@alcaeus I've just started run into this issue on a project albeit with fairly outdated packages

```
C:\wamp64\www\project>php app/console cache:clear --no-warmup

Fatal error: Class 'Memcached' not found in C:\wamp64\www\project\vendor\doctrine\doctrine-cache-bundle\Tests\Functional\Fixtures\Memcached.php on line 7

```

Windows 7 x64
PHP 7.1.13
Symfony 3.0
Memcache Extension installed (from https://github.com/nono303/PHP7-memcache-dll)

**Comment by alcaeus** [comment]
@The-Don-Himself did you verify that you have installed the extension for both CLI and web SAPI? Depending on your platform you'll need to separately enable it. You can easily check whether it's there by running `php -m` and checking for the `memcached` line.

**Comment by The-Don-Himself** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>php -m
[PHP Modules]
bcmath
bz2
calendar
Core
couchbase
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
gmp
grpc
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
memcache
mongodb
mysqli
mysqlnd
OAuth
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]


C:\Windows\system32>

**Comment by alcaeus** [comment]
You've installed `memcache` when you need to install `memcached` (note the `d` at the end). That's why this isn't working for you.

**Comment by The-Don-Himself** [comment]
I'm sure the module is enabled in both environments cli and web.
However, your previous comment that it was amended in the latest versions proves true, so I've temporarily updated the codebase, but will have to downgrade again once I deliver the project back.

If the only workaround is to use the latest version then I'm happy to just update and downgrade, but if there is a cleaner method I'd love to hear it :)

**Comment by The-Don-Himself** [comment]
Hadn't noticed your comment above, sorry. Problem noted then, thanks.
