### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by smilesrg** [doctrine/DoctrineCacheBundle#29]
I'm not able to create issues on doctrine/cache so I'll just leave it here.

Probably there are memoty leaks in the library ```doctrine/cache```, I noticed similar issues with APC too. I used v1.3.0.

```2014/12/05 15:39:13 [error] 15961#0: *72120 FastCGI sent in stderr: "PHP message  : PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to a  llocate 26593710 bytes) in /var/www/myhost.com/shared/vendor/doctrine/cache/  lib/Doctrine/Common/Cache/RedisCache.php on line 83" while reading response head  er from upstream, client: 173.245.48.196, server: api.myhost.com, request: "  GET /martinfabricius/likes/153 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000",   host: "myhost.com"```

**Comment by smilesrg** [comment]
@stof maybe you have any ideas why this happens?

**Comment by guilhermeblanco** [comment]
I have no way to reproduce this issue. Please upgrade to doctrine/cache 1.4 and try to possibly isolate this in a test case, then reopen this issue for further considerations.
