### ISSUE TITLE
Alias may not work well

### ISSUE THREAD

**Issue by tua** [doctrine/DoctrineCacheBundle#30]
For custom providers, if  doctrine_cache.providers.select2_cache is a dependency service for other services,  it may throw non existing service, see below:

```yml

doctrine_cache:

    # this works
    aliases:
        doctrine_cache.providers.select2_cache: data_cache

    custom_providers:
        doctrine_cache_predis:
            prototype:  "prefix.doctrine_cache_predis"

        data_cache:
            ........
            doctrine_cache_predis: ~
            # this will not work
            aliases:
                - doctrine_cache.providers.select2_cache

**Comment by guilhermeblanco** [comment]
Your understanding of custom_providers is wrong.
A custom_provider is not a service, but a group of parameters (provider type and definition class) that are later reused when creating a provider. There's no aliasing support for custom_providers.
Closing as invalid.
