### ISSUE TITLE
xmlns/xsi/xsd url not reachable

### ISSUE THREAD

**Issue by JHGitty** [doctrine/DoctrineCacheBundle#35]
The urls in the documentation example are not reachable (HTTP-Code 404 error.)

http://doctrine-project.org/schemas/symfony-dic/cache
http://doctrine-project.org/schemas/symfony-dic/cache/doctrine_cache-1.0.xsd

**Comment by stof** [comment]
http://doctrine-project.org/schemas/symfony-dic/cache is not an URL. It is the XML namespace. It is not meant to be a reachable URL.

**Comment by JHGitty** [comment]
@stof Ok, what's about the xsd file in the same path? I think it should be reachable?

**Comment by gimler** [comment]
the xml example doesn't work http://doctrine-project.org/schemas/symfony-dic/cache/doctrine_cache-1.0.xsd is not found.

**Comment by alcaeus** [comment]
@jwage what options do we have for hosting static files like the schema config in this case? We could either fetch the schema and deploy it to the website or update the documentation to use permanent links at GitHub, what do you think?

**Comment by Majkl578** [comment]
Right now it's part of the website: https://github.com/doctrine/doctrine-website/tree/master/source/schemas

**Comment by alcaeus** [comment]
Closing for the reason stated in #156.
