### ISSUE TITLE
Getting rid of a symfony/framework-bundle requirement

### ISSUE THREAD

**Issue by EllisV** [doctrine/DoctrineCacheBundle#40]
Currently this bundle requires symfony/framework-bundle because `Doctrine\Bundle\DoctrineCacheBundle\Command\CacheCommand` extends `Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand`. To not make an application which does not use symfony/framework-bundle but uses symfony/http-kernel component to install unnecessary bundle you can make CacheCommand an implementation of `Symfony\Component\DependencyInjection\ContainerAwareInterface`.

**Comment by guilhermeblanco** [comment]
Issue is fixed through merged PR #41
