### ISSUE TITLE
Redis fetch multiple looks up cached values by cache key, lib returns by numeric ID

### ISSUE THREAD

**Issue by vvondra** [doctrine/DoctrineCacheBundle#51]
`doFetchMultiple` in RedisCache looks up the returned values by cache key, but the implementation docs say items are returned with numeric IDs corresponding to key order:
```php
 /**
     * Returns the values of all specified keys.
     *
     * For every key that does not hold a string value or does not exist,
     * the special value false is returned. Because of this, the operation never fails.
     *
     * @param array $array
     * @return array
     * @link http://redis.io/commands/mget
     * @example
     * <pre>
     * $redis->delete('x', 'y', 'z', 'h');	// remove x y z
     * $redis->mset(array('x' => 'a', 'y' => 'b', 'z' => 'c'));
     * $redis->hset('h', 'field', 'value');
     * var_dump($redis->mget(array('x', 'y', 'z', 'h')));
     * // Output:
     * // array(3) {
     * // [0]=>
     * // string(1) "a"
     * // [1]=>
     * // string(1) "b"
     * // [2]=>
     * // string(1) "c"
     * // [3]=>
     * // bool(false)
     * // }
     * </pre>
     */
```

so the lookup always results in a miss

**Comment by zeroedin-bill** [comment]
Will be fixed in https://github.com/doctrine/cache/pull/78

**Comment by calumbrodie** [comment]
Out of interest how(metadata/query/result?) / where (what area/layer of code) are you using 'doFetchMultiple'? I'm looking to get into this as well but documented use patterns are non existent.

**Comment by vvondra** [comment]
Assume I have a method called `findRowsByIds(array $ids)`

No the `$ids` argument I pass almost always contains a different set of IDs, so I can't cache by the whole key and I have two options:

1. Ask for each ID in a single `fetch` query. Whenever an ID is a cache hit, remove it from the filter for the slow backend.

2. Ask for all IDs in the query, get results from cache server in one batch and then remove from the filter the IDs which have been cache hits. Cache misses continue to the slower backend.

I haven't made any performance benchmarks, but posts on the internet suggest less commands = less time spent querying cache (e.g. http://blog.huangzhimin.com/2012/04/05/redis-mget-mset-vs-get-set/)

**Comment by calumbrodie** [comment]
@vvondra So you are only using it for result cache? (Not Metadata cache or Query Cache?). For your given example can't you just do a single doctrine query anyway?

**Comment by vvondra** [comment]
I never said we used it for doctrine. We use this bundle for general caching purposes and the more IDs we ask the persistent storage for, the slower the query. So we only ask for those not cached.

**Comment by calumbrodie** [comment]
OK - makes sense thanks, not sure it fits my use case but I appreciate you taking the time to reply to me.
