### ISSUE TITLE
Disable custom cache?

### ISSUE THREAD

**Issue by slavafomin** [doctrine/DoctrineCacheBundle#52]
Hello!

Thank you for this great bundle!

But, is it possible to disable the specific cache?

For example I want to disable some cache in development environment. I can't see such an option in the docs.

Thanks!

**Comment by stof** [comment]
This bundle is only about configuring Doctrine Cache instance to be able to use them in other places. It has no knowledge of how the cache is used

**Comment by guilhermeblanco** [comment]
@slavafomin You can override the cache in an environment specific way and define the ArrayCache.
