### ISSUE TITLE
DBAL Cache Provider?

### ISSUE THREAD

**Issue by davewwww** [doctrine/DoctrineCacheBundle#54]
Hi,

I was wondering why there is no DBAL cache provider.
I would like to use it like the "SQLite3Cache", but just with a DBAL Connection instead of the "SQLite3".
Actually i build a custom provider, but it could be an official implementation.

Any thoughts about it?

**Comment by stof** [comment]
There is no such provider in the ``doctrine/cache`` library. So this bundle cannot give you the possibility to configure it.

This bundle implements only 2 functionalities:

- a way to configure Doctrine Cache instances
- an implementation of the Symfony ACL cache interface based on Doctrine Cache

It does not implement any cache provider
