### ISSUE TITLE
Load all/multiple class metadata automatically [Discussion]

### ISSUE THREAD

**Issue by calumbrodie** [doctrine/DoctrineCacheBundle#56]
This PR https://github.com/doctrine/cache/pull/29 Added functionality to perform multiple fetches on various cache implementations. Is there any scope for adding some sort of intelligent use of this within this bundle?

Thoughts:

- Option to load all class metadata for a given entity manager eagerly?
- Option to remember which class metadata was used (for a given route/service) and eagerly load it for subsequent requests?

I'm aware that I'm possibly optimising in the wrong area here so I'd be interested to hear if anyone else has similar problems (our application is quite large so the scope of some requests often means the loading of models from many parts of the systems). A well layered caching system means this isn't a terminal problem for us, but the latency/load associated with populating the metadata cache adds a significant overhead to most requests.

**Comment by stof** [comment]
This bundle is only about configuring doctrine cache instances. It has no knowledge about entity managers.

Loading metadata in batch for the ORM should be implemented in the ORM anyway, not here.

Btw I'm not sure about your idea of remember which metadata were used by each route. this would probably add more overhead than what you would solved. and in any case, it would be out of the scope of this bundle

**Comment by calumbrodie** [comment]
Understood - please close
