### ISSUE TITLE
Cache drivers configuration doesn't work for most of the drivers

### ISSUE THREAD

**Issue by Nek-** [doctrine/DoctrineCacheBundle#65]
Hello,

First of all, consider that I didn't load the DoctrineCacheBundle (I only use DoctrineBundle) but the bug is from the code of DoctrineCacheBundle, that's why I post this issue here. And it's related to #38.

I notice that the [SymfonyBridgeAdapter](https://github.com/doctrine/DoctrineCacheBundle/blob/master/DependencyInjection/SymfonyBridgeAdapter.php#L94) doesnt work for all cache definition and so it fails for example on `file_system`. The problem is that the configuration is faked only for `memcached` and `redis` (apc will work because there is no config needed). Others will fail.

Of course there is a workaround using the `doctrine_cache` configuration to create a provider and some config inside DoctrineBundle. But why keeping something that fails while you could suggest to use the other way ? I suggest to throw an exception more understandable while the cache driver is not supported by the SymfonyBridgeAdapter. Another solution is to fix the problem for all cache drivers.

(I can do it if you want)

Here is the configuration that should work but throw a PHP error:

```
doctrine:
    orm:
        result_cache_driver:
            type: file_system
```

**Comment by guilhermeblanco** [comment]
The suggestion is to create your own provider and use it as a reference inside doctrine mapping.
We keep the Bridge for BC reasons.
