### ISSUE TITLE
Memcache::delete always throws Notice

### ISSUE THREAD

**Issue by SoboLAN** [doctrine/DoctrineCacheBundle#71]
There is no possibility to open an issue on [doctrine/cache](https://github.com/doctrine/cache), so I'll open it here.

I use Doctrine Cache Bundle with Memcache and, when I do this:

```php
$memcache->setNamespace('mynamespace');
$memcache->save($mykey, 'some-data-here', 3600);
$result = $memcache->delete($mykey);
```

I always get the following Notice:

> PHP Notice: MemcachePool::delete(): Server localhost (tcp 11211, udp 0) failed with: CLIENT_ERROR bad command line format. Usage: delete [noreply]

If I replace [internally in the library](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/MemcacheCache.php#L101) this:

```php
return $this->memcache->delete($id) || ! $this->doContains($id);
```

with this:

```php
return $this->memcache->delete($id, 0) || ! $this->doContains($id);
```

Then I no longer get the notice.

This is quite interesting because, according to [PHP documentation](http://www.php.net/manual/en/memcache.delete.php):

> It's not recommended to use the **timeout** parameter.

--

Is anyone else experiencing this problem ? Or is it just me ? I suspect most people use memcache when using this library. So how come is it's not reported/fixed by now ?

**Comment by stof** [comment]
Well, the parameter is marked as deprecated, so having to use it looks weird to me.

what is your ext-memcache version ?

**Comment by Ocramius** [comment]
Could you als just check the test suite and see if that case is already covered?

**Comment by SoboLAN** [comment]
@stof: My versions are:

- PHP: **5.3.***
- memcache extension: **3.0.4**
- doctrine/cache: **1.4.2**
- doctrine/doctrine-cache-bundle: **1.0.1**

**Comment by SoboLAN** [comment]
@Ocramius I took a look now and I can't find anything in the test suite related to this.

**Comment by SoboLAN** [comment]
Based on [this post](http://www.php.net/manual/en/memcache.delete.php#98826), the notice appears because of the memcached and memcached versions that I use.

So now I know the cause for this.

I will add a subclass:

```php
class MyMemcache extends \Memcache
{
    public function delete($key, $timeout = 0)
    {
        return parent::delete($key, $timeout);
    }
}
```

and I will use that class for **doctrine-cache-bundle** services definition instead of PHP's `Memcache` class.

This will solve my problem.

---

However, do you guys think I should make a pull request on **doctrine/cache** where I change the call to include the `timeout` parameter ?

If I ran into this problem, then there are thousands of other people who (will) run into it as well.

@Ocramius What do you think ?

**Comment by stof** [comment]
@SoboLAN I suggest asking the ext-memcache devs to fix the issue (or to use ext-memcached instead of ext-memcache).

Using a deprecated argument as a workaround for the bug seems weird to me.

**Comment by SoboLAN** [comment]
@stof OK, I will leave it as is.

Thanks for the fast replies :) .
