### ISSUE TITLE
Make security-acl an optional dependency

### ISSUE THREAD

**Issue by Tobion** [doctrine/DoctrineCacheBundle#76]
IMO the symfony/security-acl dependency should be moved from require to require-dev (and suggest).

We are trying to remove ACL from the default symfony installation, see symfony/symfony#14718
And symfony/symfony 3.0 does not require security-acl anymore and security-acl is also extracted into standalone repo since 2.8.

But using symfony-standard 3.0 still installs security-acl because the doctrine cache bundle requires it.

**Comment by weaverryan** [comment]
:+1: - it is only "used" by https://github.com/doctrine/DoctrineCacheBundle/blob/master/Acl/Model/AclCache.php, correct? This is holding up DoctrineBundle's compatibility as well https://github.com/doctrine/DoctrineBundle/pull/486#issuecomment-159664695

**Comment by weaverryan** [comment]
Pull request #77
