### ISSUE TITLE
Give options to memcached driver

### ISSUE THREAD

**Issue by xavierleune** [doctrine/DoctrineCacheBundle#89]
Hi,

Actually there is no clean way to call the method "setOptions" on the memcached instance. However this is very useful.
As an example when you have multiple memcached server, it's a very good practice do use a libkatema compatible hashing algorithm.

I'll push a PR about this lack.

Thanks !

**Comment by stof** [comment]
Actually, it is, because the bundle configuration supports giving the id of a service for the Memcached connection, allowing you to configure it as you want (as you would then be responsible for configuring the service):

```yaml
doctrine_cache:
    providers:
        my_memcached_cache:
            type: memcached
            connection_id: app.memcached_connection

services:
    app.memcached_connection:
        class: Memcached
        public: false
        # more config here to fit your needs

**Comment by xavierleune** [comment]
Hi @stof and thanks for your feedback. Would you reject a PR giving the support for options ? Actually I'd prefer doing the configuration this way. What do you think about ?

**Comment by stof** [comment]
@xavierleune I cannot reject it, as I'm not maintainer on this bundle.

**Comment by xavierleune** [comment]
@stof but you don't consider this as useful ?

**Comment by alcaeus** [comment]
Defining the service manually is a workaround, but not more than that. It would definitely be useful to configure connection options directly in the configuration. I know some time has passed since the original question, but if you still want to contribute the feature that'd be great.

**Comment by alcaeus** [comment]
Closing as with the deprecation of this bundle we're no longer accepting feature PRs.
