### ISSUE TITLE
Built-in provider complains about non-existing class

### ISSUE THREAD

**Issue by anho** [doctrine/DoctrineCacheBundle#92]
Hi,

this very simple test definition:

```
doctrine_cache:
  providers:
    my_memcache:
      type: memcache
```

Gives me an exception:

```
ReflectionException in ContainerBuilder.php line 964:
Class does not exist

in ContainerBuilder.php line 964
at ReflectionClass->__construct('') in ContainerBuilder.php line 964
at ContainerBuilder->createService(object(DefinitionDecorator), 'doctrine_cache.providers.my_memcache') in ContainerBuilder.php line 490
```

As far as I've seen it, it uses an abstract built-in definition for memcache that actually has a class in its definition. Still, it fails with the message mentioned.

Anyone seeing the error?

**Comment by alcaeus** [comment]
Sorry for the long delay. I can't reproduce the issue with the latest release, so if it's still relevant please reopen this issue, ideally with a small reproducer as that would help diagnosing the issue. Thanks!
