### ISSUE TITLE
Memcached - missing class 

### ISSUE THREAD

**Issue by xsuntel** [doctrine/DoctrineCacheBundle#95]
Hi guys

Currently I have an issue about PHP Fatal error : Class 'Memcached' not found in ...

I have tested the DoctineCacheBundle of Symfony on XAMPP (Windows) and IDE is phpstorm. 

for 1 week, I checked configuration as below.

# Doctrine Cache
doctrine_cache:
    providers:
        service_connection_memcached_provider:
            memcached:
                connection_id: "memcached"

services:
    memcached:
        class: Memcached
        calls:
            - [ addServers, [ "%memcached_servers%" ]]
    cache_memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [ setMemcached, ['@memcached']]

parameters:
    memcached_servers:
        - { host: cache.amazonaws.com, port: 11211 }
        - { host: cache.amazonaws.com, port: 11211 }

I think that this isssue is not in my notebook (XAMPP, PHPSTORM). because I'm using memcached servers on AWS (Amazon Web Service)

and I saw a message about  missing class of Memcached on PHPSTORM.

Can you give me an advice ?

Regards

Ryan

**Comment by xabbuh** [comment]
You seem to miss the [Memcached extension](http://php.net/manual/en/book.memcached.php).

**Comment by mikeSimonson** [comment]
Closing as the issue seems fixed.
