### ISSUE TITLE
question: Metadata caching fails on PHP7 phpredis

### ISSUE THREAD

**Issue by napalm33700** [doctrine/DoctrineCacheBundle#98]
Metadata caching fails on PHP7 phpredis because of igbinary.
So is there a way to change default RedisCache so that serializer is Redis::SERIALIZER_PHP and not 
Redis::SERIALIZER_IGBINARY ?

I don't want to recompile a phpredis extension without igbinary in it.

**Comment by gsdevme** [comment]
We also noticed this, we basically switched to using predis for now.

**Comment by mikeSimonson** [comment]
@napalm33700 What do you mean "because of igbinary" ?
Can you make a failing test case ?

**Comment by napalm33700** [comment]
Same issue with another bundle [https://github.com/snc/SncRedisBundle/issues/259](url), after  
PHPredis must be installed with igbinary

**Comment by mikeSimonson** [comment]
This is thus a igbinary issue with php7. The work to make the tests pass on php7 is not finished yet.

**Comment by napalm33700** [comment]
Yes but in the meantime, is there a way to change RedisCache serializer to Redis::SERIALIZER_PHP if there is igbinary ?

**Comment by mikeSimonson** [comment]
@napalm33700 You can create your [custom provider](https://symfony.com/doc/current/bundles/DoctrineCacheBundle/custom_providers.html) that is going to be a copy of the doctrine redis one except that the getSerializerValue will return Redis::SERIALIZER_PHP in every case.

Then you can maybe make a PR to make that configurable in the Redis doctrine cache implementation.

**Comment by g-alonso** [comment]
> Yes but in the meantime, is there a way to change RedisCache serializer to Redis::SERIALIZER_PHP if there is igbinary ?

    ```
$resultCache = new \Doctrine\Common\Cache\RedisCache();
    $resultCache->setRedis($redis);
    $resultCache->getRedis()->setOption(Redis::OPT_SERIALIZER, Redis::SERIALIZER_PHP); // override
```
